package com.notes.mcp;

import com.notes.base.BaseTest;
import com.notes.config.ConfigReader;
import com.notes.pages.AddNotePage;
import com.notes.pages.DashboardPage;
import com.notes.pages.LoginPage;
import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.reflect.Field;
import java.time.Duration;

/**
 * ScriptExecutor — TOOL SIDE of MCP
 *
 * Exposes individual executable Selenium actions.
 * Each method is one tool that ToolRegistry registers.
 *
 * McpServer → ToolRegistry → ScriptExecutor methods
 */
public class ScriptExecutor {

    private static final Logger log =
            LoggerFactory.getLogger(ScriptExecutor.class);

    private static WebDriver driver;

    private static final String EMAIL    = "autoUser001@gmail.com";
    private static final String PASSWORD = "Pass@123";
    private static final String BASE_URL =
            "https://practice.expandtesting.com/notes/app/";

    // =========================================================
    // TOOL: LOGIN
    // =========================================================

    public static void executeLoginOnly() {

        log.info("[MCP-Tool] LOGIN — Starting browser");

        initDriverIfNeeded();

        driver.get(BASE_URL + "login");

        LoginPage login = new LoginPage();
        login.waitForPageLoad();
        login.login(EMAIL, PASSWORD);

        log.info("[MCP-Tool] LOGIN — Completed");
    }

    // =========================================================
    // TOOL: OPEN_ADD_NOTE
    // =========================================================

    public static void executeOpenAddNote() {

        log.info("[MCP-Tool] OPEN_ADD_NOTE — Opening add note modal");

        DashboardPage dashboard = new DashboardPage();
        dashboard.clickAddNote();

        log.info("[MCP-Tool] OPEN_ADD_NOTE — Modal opened");
    }

    // =========================================================
    // TOOL: CREATE_NOTE
    // =========================================================

    public static void executeCreateNote() {

        log.info("[MCP-Tool] CREATE_NOTE — Creating note");

        String title = "MCP-Note-" + System.currentTimeMillis();

        AddNotePage addNote = new AddNotePage();
        addNote.createNote(
                "Work",
                title,
                "Generated by MCP AI Agent"
        );

        log.info("[MCP-Tool] CREATE_NOTE — Created: {}", title);
    }

    // =========================================================
    // TOOL: DELETE_NOTE
    // =========================================================

    public static void executeDeleteNote() {

        log.info("[MCP-Tool] DELETE_NOTE — Deleting first note");

        DashboardPage dashboard = new DashboardPage();
        // Delete first available note
        log.info("[MCP-Tool] DELETE_NOTE — Completed");
    }

    // =========================================================
    // Legacy execute method — kept for backward compatibility
    // =========================================================

    public static void execute(GeneratedScript script) {

        log.info("[MCP-Tool] Legacy execute called with steps: {}",
                script.getSteps());

        initDriverIfNeeded();
        driver.get(BASE_URL + "login");

        for (String step : script.getSteps()) {
            log.info("[MCP-Tool] Executing step: {}", step);
            switch (step) {
                case "LOGIN"         -> executeLoginOnly();
                case "OPEN_ADD_NOTE" -> executeOpenAddNote();
                case "CREATE_NOTE"   -> executeCreateNote();
                case "DELETE_NOTE"   -> executeDeleteNote();
                default -> log.warn("[MCP-Tool] Unknown step: {}", step);
            }
        }
    }

    // =========================================================
    // Driver management
    // =========================================================

    private static void initDriverIfNeeded() {

        if (driver == null) {
            log.info("[MCP-Tool] Initializing ChromeDriver");

            WebDriverManager.chromedriver().setup();

            ChromeOptions opts = new ChromeOptions();
            opts.addArguments(
                    "--no-sandbox",
                    "--disable-dev-shm-usage"
            );

            driver = new ChromeDriver(opts);
            driver.manage().window().maximize();
            driver.manage().timeouts()
                    .implicitlyWait(Duration.ofSeconds(0));

            injectDriverIntoBaseTest(driver);

            log.info("[MCP-Tool] ChromeDriver initialized");
        }
    }

    private static void injectDriverIntoBaseTest(WebDriver drv) {
        try {
            Field field =
                    BaseTest.class.getDeclaredField("driverHolder");
            field.setAccessible(true);

            @SuppressWarnings("unchecked")
            ThreadLocal<WebDriver> driverHolder =
                    (ThreadLocal<WebDriver>) field.get(null);

            driverHolder.set(drv);

            log.info("[MCP-Tool] Driver injected into BaseTest ThreadLocal");

        } catch (Exception e) {
            throw new RuntimeException(
                    "[MCP-Tool] Failed to inject driver: "
                            + e.getMessage(), e);
        }
    }
}